### ISSUE TITLE
Exception when trying to use with Varta pulse neo

### ISSUE THREAD

**Issue by HeavyWombat** [Vip0r/vartastorage#3]
Hey! First of all, thank you very much for this project. I am looking forward to see it used in Home Assistant.

I have been looking into using it already as a custom component, but failed to get it configured. So I went ahead and wanted to try to use it standalone.

The problem seems to be that my Varta pulse neo does not serve any `/cgi` paths at all. To try it out, I commented out `get_serial` and `get_energy_cgi` calls and that made it work for me. It reports values that roughly correlate with what is shown on the Varta Energy Dashboard.

Is there anything wrong with my setup that the battery is not serving `cgi` paths? Or, would it be possible to have the calls that rely on the CGI thingy to be optional? Thanks in advance for your feedback.

**Comment by HeavyWombat** [comment]
BTW, the traceback looks like this:
```
Traceback (most recent call last):
  File "/home/foobar/.local/lib/python3.10/site-packages/vartastorage/client.py", line 52, in get_all_data
    out["serial"] = self.get_serial()
  File "/home/foobar/.local/lib/python3.10/site-packages/vartastorage/client.py", line 195, in get_serial
    return result
UnboundLocalError: local variable 'result' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foobar/varta/main.py", line 7, in <module>
    varta.get_all_data()
  File "/home/foobar/.local/lib/python3.10/site-packages/vartastorage/vartastorage.py", line 15, in get_all_data
    data = self.client.get_all_data()
  File "/home/foobar/.local/lib/python3.10/site-packages/vartastorage/client.py", line 63, in get_all_data
from vartastorage.vartastorage import VartaStorage
    raise ValueError("An error occured while trying to poll all data fields. Please check your connection")
ValueError: An error occured while trying to poll all data fields. Please check your connection
```

**Comment by Santobert** [comment]
Maybe it would be better to use the `cgi` endpoint only when they are available. The serial number is available via modbus aswell (register 1054, as string10).

**Comment by juekr** [comment]
I have a Neo Pulse as well and a kinda similar problem, but my error message is different:
```
Traceback (most recent call last):
  File "/Users/xx/_DEV/smarthome/.venv/lib/python3.11/site-packages/vartastorage/client.py", line 52, in get_all_data
    out["serial"] = self.get_serial()
                    ^^^^^^^^^^^^^^^^^
  File "/Users/xx/_DEV/smarthome/.venv/lib/python3.11/site-packages/vartastorage/client.py", line 195, in get_serial
    return result
           ^^^^^^
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
```

When I then comment the `get_serial()` function out, another error pops up when calling `self.client.get_all_data()`:
```
ValueError: An error occured while trying to poll all data fields. Please check your connection
```

What can I do?

**Comment by Vip0r** [comment]
Hey,

i now seperated the CGI and MODBUS part in the new release of the package (0.2.7)

Could you give it a try?
